### ISSUE TITLE
read_data syntax error

### ISSUE THREAD

**Issue by testlolla** [ThFriedrich/lammps_vscode#39]
**Describe the bug**
So the extension say that a file doesn't exist in my folder but it does. 

**To Reproduce**
go to a folder with any data files. Open a lammps script and type:
read_data data_file_name

**Expected behavior**
There shouldn't be a red underline.

**Screenshots**
<img width="1050" alt="Screen Shot 2022-06-21 at 1 13 56 PM" src="https://user-images.githubusercontent.com/72363318/174858978-c8f48bd6-a8d4-48ec-b769-e30d1da80a98.png">

**Comment by ThFriedrich** [comment]
Hi @testlolla,
thanks for reporting this. However, I can't seem to reproduce this. Can you check, you are using the latest version? Another reasons I could imagine is: Perhaps you changed the 'file_name' from something wrong to something correct, and the error didn't disappear automatically? (That would be because all the checks are triggered only on certain events, like saving the file for example, which is just more efficient than using a timer.)  Otherwise I'd need more context, especially your OS could be relevant.
