### ISSUE TITLE
The file does not exist

### ISSUE THREAD

**Issue by cmbsnr** [ThFriedrich/lammps_vscode#51]
**Describe the bug**
There is an error "The file *.data does not exist" but the file exist. And the script can be run correctly by LAMMPS.

**To Reproduce**
1. Go to VSCode and start to write a LAMMPS script with the extension. 
2. Copy a *.data to the directory.
![image](https://user-images.githubusercontent.com/89567301/233627902-562628fe-72f4-43e1-9ff4-6921ee36400c.png)
3. Write the command "read_data".
4. See error.
![image](https://user-images.githubusercontent.com/89567301/233628043-e0421e06-dc89-4ce9-9736-2ad47038fd7f.png)

**Expected behavior**
If the input file does not exist, report the error. But DOES NOT report the error when the input file exist.

**Screenshots**
Above.

**Desktop (please complete the following information):**
 - OS: Windows and Linux.
 - Version [v1.5.14]

**Comment by ThFriedrich** [comment]
Hi @cmbsnr . Thanks for your Bug-Report.
I've just pushed an update that changes the path-checks to relate to the script-path, rather than the current working directory. This was indeed clearly a bug. I am not a 100% sure this will fix your issue, but I suspect it will. I will close the issue. Please reopen if problems persist. The update will ship with the next release shortly.
